
# port 9600 API listener - http only at present
http.host: "0.0.0.0"

pipeline.unsafe_shutdown: true

path.data: /usr/share/logstash/data/

#log.level: debug

config.reload.automatic: true
config.reload.interval: 5s

# No metricbeats included in the container so use legacy monitoring
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: [ "http://es01:9200" ]

